### PR TITLE
Bump Flutter version to 3.24

### PR DESCRIPTION
**Pull request by ivonasto**
Changed some method signatures and fields which are different in Flutter 3.24. 

Ran on an Android device, can somebody test it works on iOS? Unit tests pass.

Also, when I try to access the wallet, it says the app is not set up to save the pass. Was it like this?

### CODE REVIEW

**Comment by etabakov** [comment]
Awesome! 
I can test it on iOS.
Regarding the wallet - I think it should work, but I have only tested it with emulators as I don't have a physical device.

**Comment by ivonasto** [comment]
Thank you! 
Regarding the wallet, I will check what I have missed on Monday and see if I can make it work.

**Comment by etabakov** [comment]
Both iOS and Android apps look quite different from the current version:
simulator_screenshot_5A1A7C8F-1672-402F-A8D6-0728BA0EAB0E
simulator_screenshot_09B7FC4C-E1E1-4BD2-BB29-2D3ACBEE9AD2

Attaching the current version for reference:
image
image

My guess is some default styles that we haven't overridden have changed.

**Comment by etabakov** [comment]
Also, can you give me write access to your fork, so I can push some iOS related changes? Or you can pull them from this branch if you prefer: https://github.com/5kmrun-bg/fivekmrun-app/tree/ivonasto-master

**Comment by ivonasto** [comment]
Found where the UI changes come from.  After version 3.16, the Material 3 library is the default and a temporary fix is to set it to false: `darkTheme: ThemeData( ..., 
          useMaterial3: false, ...)` until the app has migrated to it.

**Comment by etabakov** [comment]
Awesome! This sounds like a great fix for the time being.

For the Google Wallet, not sure if you joined the Discord server but there is a discussion there that might help: https://discord.com/channels/1168808233830469693/1168808506888048741

**Comment by etabakov** [comment]
ОК ... the application looks good now. A few outstanding items:

- [ ] Update the README instructions with the Flutter version that should be installed
- [ ] Update the deployment workflow to use the respective version of Flutter
- [ ] Verify the add to wallet function works on Android
- [ ] I noticed on iOS on startup the app throws the following exception that needs to be checked as it may break the push notifications (I will take care for that)

`ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
<asynchronous suspension>
#3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:248:11)
<asynchronous suspension>
#4      PushNotificationsManager.init (package:fivekmrun_flutter/push_notifications_manager.dart:93:23)`

**Comment by etabakov** [comment]
Tested the Google Wallet with emulator and works as expected:
Screenshot_1731358435

Let's update the deployment and README and this is good to go.

**Comment by etabakov** [comment]
@ivonasto this is good to go 🙏 Thanks for your effort - it's always nice to run on the latest stack!

**Pull request merged**
